AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an LDAP service
Parameters:
  ClusterStackName:
      Description: Stack name of the ECS cluster to deply the serivces
      Type: String
      Default: gerrit-cluster
  DomainName:
    Description: "FQDN of the domain for this directory"
    Type: String
    Default: gerritforge.gerritforgeaws.com
  SimpleADShortName:
    Description: "Netbios name of the domain for this directory"
    Type: String
    Default: gerritforge
  EnableSingleSignOn:
    Description: "Enable SSO"
    Type: String
    Default: false
  CreateAlias:
    Description: "Only required for applications which need a URL to connect to the directory"
    Type: String
    Default: false
  SimpleADPW:
    Description: "Domain admin Password"
    Type: String
    NoEcho: true
    Default: Pass@w0rd
  Size:
    Description: "Size of the Simple AD"
    Type: String
    Default: Small

Resources:
  SimpleLDAP:
    Type: AWS::DirectoryService::SimpleAD
    Properties:
      CreateAlias: !Ref CreateAlias
      EnableSso: !Ref EnableSingleSignOn
      Name: !Ref DomainName
      Password: !Ref SimpleADPW
      ShortName: !Ref SimpleADShortName
      Size: !Ref Size
      VpcSettings:
        SubnetIds:
          - Fn::ImportValue:
              !Join [':', [!Ref 'ClusterStackName', 'PublicSubnetOne']]
          - Fn::ImportValue:
              !Join [':', [!Ref 'ClusterStackName', 'PublicSubnetTwo']]
        VpcId:
          Fn::ImportValue:
              !Join [':', [!Ref 'ClusterStackName', 'VPCId']]

Outputs:
  DirectoryID:
    Description: "ID of the SimpleAD"
    Value: !Ref SimpleLDAP
  PrimaryDNS:
    Description: "Primary DNS IPs of the SimpleAD"
    Value:
      Fn::Select:
        - 0
        - Fn::GetAtt:
          - SimpleLDAP
          - DnsIpAddresses
  SecondaryDNS:
    Description: "Secondary DNS IPs of the SimpleAD"
    Value:
      Fn::Select:
        - 1
        - Fn::GetAtt:
          - SimpleLDAP
          - DnsIpAddresses
